title: 'rotten soymilk'

description: hrysd のブログ
keywords:
  - hrysd
  - soymilk
  - 豆乳

url: 'http://docs.hrysd.org'

permalink: /:year/:month/:day/:title/

timezone: Asia/Tokyo

markdown: redcarpet

redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink

highlighter: rouge

sass:
  sass_dir: assets/stylesheets
