title: ':soymilk:'

description: 元液体のブログ
keywords:
  - hrysd
  - soymilk
  - 豆乳

url: 'http://docs.hrysd.org'

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

markdown: redcarpet

redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink

highlighter: rouge

permalink: pretty

sass:
  sass_dir: assets/stylesheets
