title: 'rotten soymilk'

description: hrysd のブログ
keywords:
  - hrysd
  - soymilk
  - 豆乳

url: 'http://docs.hrysd.org'

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - README.md
  - Rakefile

permalink: /:year/:month/:day/:title/

markdown: redcarpet

redcarpet:
  extensions:
    - fenced_code_blocks
    - autolink

highlighter: rouge

sass:
  sass_dir: assets/stylesheets
