title: 'rotten soymilk'

description: hrysd のブログ
keywords:
  - hrysd
  - soymilk
  - 豆乳

url: 'https://docs.hrysd.org'

permalink: /:year/:month/:day/:title/

timezone: Asia/Tokyo

markdown: CommonMark

commonmark:
  options: ['UNSAFE']
  extensions:
    - autolink
    - table

highlighter: rouge

sass:
  sass_dir: assets/stylesheets
